import type { NextPage } from 'next'
import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

// for node, created .env.local file
// console.log(process.env.MONGO_URI)
// this is for non noe environments
// console.log(process.env.secretstring)





const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ilker's Notebook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Ilker's Notebook</h1>
        <div className={styles.grid}>
        <Link href="/books"><a  className={styles.card}>Books</a></Link>
        <Link href="/web-development"><a  className={styles.card}>Web Development</a></Link>
        <Link href="/marketing"><a  className={styles.card}>Marketing</a></Link>
        </div>
      </main>
      <footer className={styles.footer}>
        <Link href="https://github.com/ilci66"><a >Find me on Github</a></Link>
      </footer>
    </div>
  )
}

export default Home
